version: '3'
services:
  app1:
    build: ./app1
    ports:
      - "5001:5000"
  app2:
    build: ./app2
    ports:
      - "5002:5000"
  server1:
    build: ./server1
    ports:
      - "8081:80"
    volumes:
      - ./zoom:/var/www/project
  server2:
    build: ./server2
    ports:
      - "8082:80"
    volumes:
      - ./zoom:/var/www/project
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
      - server1
      - server2
